package kronex.fun.display.screens.clickgui.components.implement.settings.select;

import net.minecraft.client.gui.DrawContext; import net.minecraft.client.util.math.MatrixStack; import org.joml.Matrix4f;
import kronex.fun.features.module.setting.implement.SelectSetting; import kronex.fun.other.utils.display.other.animation.Direction; import kronex.fun.other.utils.display.other.animation.implement.DecelerateAnimation; import kronex.fun.other.utils.display.font.Fonts; import kronex.fun.other.utils.display.shape.ShapeProperties; import kronex.fun.other.utils.display.color.ColorAssist; import kronex.fun.other.utils.math.MathUtil; import kronex.fun.display.screens.clickgui.components.implement.settings.AbstractSettingComponent;
import java.util.ArrayList; import java.util.List; import static kronex.fun.other.utils.display.font.Fonts.Type.BOLD;
public class SelectComponent extends AbstractSettingComponent{
 private final List<SelectedButton> selectedButtons=new ArrayList<>(); private final SelectSetting setting; private boolean open; private float dropdownListX,dropDownListY,dropDownListWidth,dropDownListHeight;
 private final kronex.fun.other.utils.display.other.animation.Animation alphaAnimation=new DecelerateAnimation().setMs(300).setValue(1);
 public SelectComponent(SelectSetting setting){super(setting);this.setting=setting;alphaAnimation.setDirection(Direction.BACKWARDS);for(String s:setting.getList())selectedButtons.add(new SelectedButton(setting,s));}
 @Override public void render(DrawContext context,int mouseX,int mouseY,float delta){MatrixStack matrices=context.getMatrices();String wrapped=setting.getDescription();height=(int)(18+Fonts.getSize(12,Fonts.Type.DEFAULT).getStringHeight(wrapped)/3);List<String> fullSettingsList=setting.getList();dropdownListX=x+width-75;dropDownListY=y+20;dropDownListWidth=66;dropDownListHeight=fullSettingsList.size()*12;alphaAnimation.setDirection(open?Direction.FORWARDS:Direction.BACKWARDS);renderSelected(matrices);Fonts.getSize(14,BOLD).drawString(matrices,setting.getName(),x+9,y+6,0xFFD4D6E1);Fonts.getSize(12,Fonts.Type.DEFAULT).drawString(matrices,wrapped,x+9,y+15,0xFF878894);}
 @Override public void renderOverlay(DrawContext context,int mouseX,int mouseY,float delta){if(!alphaAnimation.isFinished(Direction.BACKWARDS))renderSelectList(context,mouseX,mouseY,delta);}
 public boolean isOpen(){return open;}
 @Override public boolean mouseClicked(double mouseX,double mouseY,int button){if(button==0){if(MathUtil.isHovered(mouseX,mouseY,x+width-75,y+4,66,14))open=!open;else if(open&&!isHoveredList(mouseX,mouseY))open=false;if(open)selectedButtons.forEach(b->b.mouseClicked(mouseX,mouseY,button));}return super.mouseClicked(mouseX,mouseY,button);}
 @Override public boolean isHover(double mouseX,double mouseY){return open&&isHoveredList(mouseX,mouseY);}
 private void renderSelected(MatrixStack matrices){rectangle.render(ShapeProperties.create(matrices,x+width-75,y+4,66,14).round(2).thickness(2).outlineColor(ColorAssist.getOutline()).color(ColorAssist.getGuiRectColor(1)).build());String selectedName=String.join(", ",setting.getSelected());Fonts.getSize(12,BOLD).drawString(matrices,selectedName,x+width-75+3,y+10,0xFFD4D6E1);rectangle.render(ShapeProperties.create(matrices,x+width-20,y+5,10,12).round(3).color(ColorAssist.getGuiRectColor(0),ColorAssist.getGuiRectColor(0),ColorAssist.getGuiRectColor(1),ColorAssist.getGuiRectColor(1)).build());}
 private void renderSelectList(DrawContext context,int mouseX,int mouseY,float delta){float opacity=alphaAnimation.getOutput().floatValue();rectangle.render(ShapeProperties.create(context.getMatrices(),dropdownListX,dropDownListY,dropDownListWidth,dropDownListHeight).round(3).thickness(2).outlineColor(ColorAssist.getOutline(opacity,1)).color(ColorAssist.getGuiRectColor(opacity)).build());float offset=dropDownListY;for(SelectedButton b:selectedButtons){b.x=dropdownListX;b.y=offset;b.width=dropDownListWidth;b.height=12;b.setAlpha(opacity);b.render(context,mouseX,mouseY,delta);offset+=12;}}
 private boolean isHoveredList(double mouseX,double mouseY){return MathUtil.isHovered(mouseX,mouseY,dropdownListX,dropDownListY-16,dropDownListWidth,dropDownListHeight+16);}
}